// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZp1K6dGvQ7GsjNtU-S-8Rt_kMbt5Ez-4',
    appId: '1:868649407040:android:87aff0d3baa5b54b9b05a5',
    messagingSenderId: '868649407040',
    projectId: 'mierp-apps',
    storageBucket: 'mierp-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd0ZWUGcKCJGonYSQanzPRhSAR9aTpqcs',
    appId: '1:868649407040:ios:454e67ef0c45ade79b05a5',
    messagingSenderId: '868649407040',
    projectId: 'mierp-apps',
    storageBucket: 'mierp-apps.firebasestorage.app',
    androidClientId: '868649407040-5drl6ti1gfgsb4sne1r8331piuhvq7jv.apps.googleusercontent.com',
    iosClientId: '868649407040-ul04ocjpdvp0kjamm9njlh8eb74tgs4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.mierpApps',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJz_psoWbflFVUKNX-rAU21bi-JF5xLY',
    appId: '1:868649407040:web:94be4b4495e5817c9b05a5',
    messagingSenderId: '868649407040',
    projectId: 'mierp-apps',
    authDomain: 'mierp-apps.firebaseapp.com',
    storageBucket: 'mierp-apps.firebasestorage.app',
    measurementId: 'G-F9P3P7VH4P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd0ZWUGcKCJGonYSQanzPRhSAR9aTpqcs',
    appId: '1:868649407040:ios:454e67ef0c45ade79b05a5',
    messagingSenderId: '868649407040',
    projectId: 'mierp-apps',
    storageBucket: 'mierp-apps.firebasestorage.app',
    androidClientId: '868649407040-5drl6ti1gfgsb4sne1r8331piuhvq7jv.apps.googleusercontent.com',
    iosClientId: '868649407040-ul04ocjpdvp0kjamm9njlh8eb74tgs4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.mierpApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnJz_psoWbflFVUKNX-rAU21bi-JF5xLY',
    appId: '1:868649407040:web:99cf9fa9dae6deb49b05a5',
    messagingSenderId: '868649407040',
    projectId: 'mierp-apps',
    authDomain: 'mierp-apps.firebaseapp.com',
    storageBucket: 'mierp-apps.firebasestorage.app',
    measurementId: 'G-3CK94C71HB',
  );

}